version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Initialize Keystore File
          command: |
            print $KEYSTORE_BASE64
            echo $KEYSTORE_BASE64 | base64 --decode > app/aykutasilkeystore
      # Set Fabric Api Key with environment variables
      - run:
          name: Initialice Fabric Properties
          command: |
            echo "apiKey=$FABRIC_API_KEY" >> app/fabric.properties
            echo "apiSecret=$FABRIC_API_SECRET" >> app/fabric.properties
            cat app/fabric.properties
      - run:
          name: Initialize Keystore File
          command: |
             echo "signingKeyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
             echo "signingKeyAliasPassword=$KEYSTORE_KEY_ALIAS_PASSWORD" >>  keystore.properties
             echo "signingStoreFile=$KEYSTORE_STORE_FILE" >>  keystore.properties
             echo "signingStorePassword=$KEYSTORE_STORE_PASSWORD" >>  keystore.properties
             cat keystore.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          command: echo "Current Branch:" ${CIRCLE_BRANCH}
      - run:
          name: Initial build
          command: ./gradlew assembleDebug assembleRelease --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - deploy:
          name: Deploy to Fabric
          command: ./gradlew crashlyticsUploadDistributionRelease --stacktrace --debug --no-daemon
workflows:
  version: 2
  workflow:
    jobs:
    - build