version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # Set Fabric Api Key with environment variables
      - run: echo "apiKey=$FABRIC_API_KEY" >> local.properties
      - run: cat local.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          command: echo "Current Branch:" ${CIRCLE_BRANCH}
      - run: cat local.properties
      - run: cat app/fabric.properties
      - run:
          name: Initial build
          command: ./gradlew assembleDebug --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - deploy:
          name: "Deploy to Fabric"
          command: ./gradlew crashlyticsUploadDistributionDebug --stacktrace --debug --no-daemon
workflows:
  version: 2
  workflow:
    jobs:
    - build